### ISSUE TITLE
eWASM prototype todo

### ISSUE THREAD

**Issue by wanderer** [ethereum/evm2.0-design#8]
- [ ] test RPC prototype
  - [ ] VM run levels
    - [ ] tx
    - [ ] block
    - [x] code
  - [ ] Store blocks
  - [x] Make blocks
  - [x] Make Txs - reuse etheruemjs-tx
- [ ] AST transformation
  - [ ] create streaming transformation for gas injections (currently not streaming) - on hold till stable binary
  - [ ] add streaming ewasm validator (restricts wasm to i32 and i64's) - on hold till stable binary
  - [x] basic
- [ ] test Network
  - [ ] Simple PoS? / PoW 
- [ ] EVM -> WASM transpiler

**Comment by wanderer** [comment]
re;ated https://github.com/ethereum/evm2.0-design/issues/2

**Comment by mko-io** [comment]
WASM for ethereum is smart choice !!

**Comment by wanderer** [comment]
moving to https://github.com/ethereumjs/ewasm-kernel/
